// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsgsfqtwzjfmmdyvahle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZ3NmcXR3empmbW1keXZhaGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjQwNTYsImV4cCI6MjA2NjAwMDA1Nn0.cjIjFYPw3gk6wCwwM_5Suh-T_GWSMbLLm-il2pDTXPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);